services:
  amnezia-web-ui:
    image: alexishw/amneziawg-web-ui:master
    build: .
    container_name: amnezia-web-ui
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}/tcp"
      - "${DEFAULT_PORT}:${DEFAULT_PORT}/udp"
    env_file:
      - .env
    volumes:
      - amnezia-data:/etc/amnezia
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    restart: unless-stopped
volumes:
  amnezia-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./amnezia-data